export const SET_HEADER_TITLE = 'set_header_title'
export const LOGIN_SUCCESS = 'login_sucess'
export const LOGIN_Fail = 'login_fail'
export const LOG_OUT = 'log_out'
export const SET_LOGS = 'set_logs'